### ISSUE TITLE
Official Nuget package

### ISSUE THREAD

**Issue by Mailaender** [meebey/SmartIrc4net#33]
The unoffical https://www.nuget.org/packages/SmartIrc4net/ even comes with typos in the DLL name:

![image](https://cloud.githubusercontent.com/assets/756669/8507906/69801d1a-2258-11e5-9366-af41e2abfca0.png)

Can't really take it serious. Please provide an official one also for additional trust.

**Comment by meebey** [comment]
ROFL. I think I tried once to make an official one but something went wrong, I don't remember what.

**Comment by Mailaender** [comment]
@RoyCurtis: Could you add @meebey as maintainer and provide your nuspec files?

**Comment by RoyCurtis** [comment]
Sorry; I had forgotten about the package. I no longer have the original .nuspec files but one can be generated using [NuGet Package Explorer](https://npe.codeplex.com/) and the [package file](https://www.nuget.org/api/v2/package/SmartIrc4net/0.4.5.1).

@meebey: Can you please confirm that [this is your NuGet Gallery profile](https://www.nuget.org/profiles/meebey)? I can transfer ownership. I have unlisted the package in the meantime.

It should be noted that [there is a more recent package in the gallery](https://www.nuget.org/packages/smartirc4net-2015/).

**Comment by Mailaender** [comment]
It is packaging an unreleased version though. There is no 0.5.9 in https://github.com/meebey/SmartIrc4net/releases and it also has a dependency at least I don't want.

**Comment by meebey** [comment]
@RoyCurtis yes that is my nuget account

**Comment by RoyCurtis** [comment]
Thanks; I have added you as an owner. Please [remove me](https://www.nuget.org/packages/SmartIrc4net/ManagePackageOwners) when you get the chance

**Comment by Mailaender** [comment]
> Sorry; I had forgotten about the package. I no longer have the original .nuspec files but one can be generated using NuGet Package Explorer and the package file.

You can also do it on Linux via the command line. See http://docs.nuget.org/Create/Creating-and-Publishing-a-Package

**Comment by meebey** [comment]
@RoyCurtis  https://www.nuget.org/account/Packages is not showing any packages

**Comment by RoyCurtis** [comment]
According to the owner list, your addition is still "pending approval". [IIUC](https://docs.nuget.org/create/managing-package-owners), you should have been sent an email confirming this, allowing you to accept. I'll remove and re-add you to send another

**Comment by meebey** [comment]
Ok that worked, thank you!

**Comment by cH40z-Lord** [comment]
Any news on this?

**Comment by Mailaender** [comment]
You can also go for the cheap route and upload DLLs to existing tagged https://github.com/meebey/SmartIrc4net/releases. I did that in the past when upstream wasn't able to handle release management on it's own. See https://github.com/OpenRA/Eluant/releases for example.

**Comment by meebey** [comment]
Starting with the SmartIrc4net version 1.1 release, it is now officially available on nuget: https://www.nuget.org/packages/SmartIrc4net/
